name: format

on:
  push:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt install -y clang-format
      - name: Format check
        run: make format
